name: Deploy static site to GitHub Pages

on:
  push:
    branches:
      - feature/deploy-pages
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node (for build step if needed)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Ensure site directory exists
        run: |
          if [ ! -d "site" ]; then echo "site directory not found"; exit 1; fi

      - name: Configure Pages
        uses: actions/configure-pages@v3

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
